### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by RichardWangRZ** [RichardWangRZ/BME547-Spring2022#14]
I encounter an error when I was doing my assignment, and I have no idea how to fix that. Would you please help me with that?
It is an error when I test the function `create_dictionary`. Here is the code:

![image](https://user-images.githubusercontent.com/97194861/154146615-048c93c1-0e0a-4a30-b7b1-7b6ac00fba2e.png)
![image](https://user-images.githubusercontent.com/97194861/154146531-a89f0fb0-9377-468c-afde-8f24734980da.png)

And the error:

![image](https://user-images.githubusercontent.com/97194861/154146685-9c4ff1a7-30e4-4c60-8a13-074aae614571.png)

**Comment by dward2** [comment]
Would you please open an issue in your GitHub Classroom repository where the code actually exists, and then put in a permalink to the code line that is causing the error?  thanks.
